# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e675e3c1759c79d5342677873dd30e3a38cea20ceeee8872c1789903c1cc2363f5cd9d1ae6b981018f22bec926433951cdabed8f95ad06a7523ae5dab12062

test:
  secret_key_base: 1621ef5e8d6fe92bfe4845b901ecfa881d58dded4e695db316c93bc2af352aaadbc5c87f9630bcc0dda0459b6281076e04fa72d9a599f20953b32f78d9d02a20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
